export const FETCH_GAME_START = "FETCH_GAME_START";
export const FETCH_GAME_SUCCESS = "FETCH_GAME_SUCCESS";
export const FETCH_GAME_FAILED = "FETCH_GAME_FAILED";

export const LOAD_GAME = "LOAD_GAME";

export const HANDLE_ANSWERS = "HANDLE_ANSWERS";
export const PRESUBMIT_HANDLER = "PRESUBMIT_HANDLER";
export const REFRESH_GAME = "REFRESH_GAME";
export const CALCULATE_SCORE = "CALCULATE_SCORE";

export const GUIDE_THE_USER = "GUIDE_THE_USER";
